spring.application.name=cursos-service
server.port=8081

# Oracle Autonomous Database
spring.datasource.url=jdbc:oracle:thin:@plataformacursos_low?TNS_ADMIN=${ORACLE_TNS_ADMIN:../oracle/wallet}
spring.datasource.username=${ORACLE_DB_USERNAME:ADMIN}
spring.datasource.password=${ORACLE_DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Pool de conexiones
spring.datasource.hikari.pool-name=CursosOraclePool
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Amazon S3
aws.region=us-east-1
aws.s3.bucket=duoc-plataforma-cursos

# Archivos
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB