spring.application.name=bff-service
server.port=8080

services.cursos.url=http://localhost:8081
services.inscripciones.url=http://localhost:8082

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin123